# Generated by Django 4.2.3 on 2023-07-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='firearm',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
