# Generated by Django 4.2.3 on 2023-07-31 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_alter_drill_name_alter_firearm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='DrillSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.drill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.skill')),
            ],
            options={
                'db_table': 'drill_skill',
            },
        ),
        migrations.AddConstraint(
            model_name='drillskill',
            constraint=models.UniqueConstraint(fields=('drill', 'skill'), name='unique_drill_skills'),
        ),
    ]
