# Generated by Django 4.2.3 on 2023-07-31 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_skill_name_drillskill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drill',
            name='skill_type',
        ),
    ]
