# Generated by Django 4.2.3 on 2023-08-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_drill_skills_delete_drillskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirearmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'firearm_type',
            },
        ),
        migrations.CreateModel(
            name='StringDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yards'), (1, 'Feet'), (2, 'Meters')], default=0, null=True)),
            ],
            options={
                'db_table': 'drill_string_distance',
            },
        ),
        migrations.CreateModel(
            name='StringParTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('note', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'drill_string_par',
            },
        ),
        migrations.CreateModel(
            name='TargetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('color', models.PositiveSmallIntegerField(choices=[(0, 'No Color/Standard'), (1, 'Black'), (2, 'Orange'), (3, 'Blue'), (4, 'Green'), (5, 'Red'), (9, 'Other')], default=0)),
                ('target_url_1', models.URLField(blank=True, max_length=255, null=True)),
                ('target_url_2', models.URLField(blank=True, max_length=255, null=True)),
                ('target_url_3', models.URLField(blank=True, max_length=255, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='target_images/')),
            ],
            options={
                'db_table': 'target_type',
            },
        ),
        migrations.RenameField(
            model_name='score',
            old_name='a_zone_hits',
            new_name='zone_hits_1',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='c_zone_hits',
            new_name='zone_hits_2',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='d_zone_hits',
            new_name='zone_hits_3',
        ),
        migrations.RemoveField(
            model_name='drill',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='drill',
            name='target_url',
        ),
        migrations.AddField(
            model_name='firearm',
            name='manufacturer',
            field=models.CharField(default='Other', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='zone_hits_10',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='zone_hits_4',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='zone_hits_5',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='zone_hits_6',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='zone_hits_7',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='zone_hits_8',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='zone_hits_9',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='string',
            name='distance_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yards'), (1, 'Feet'), (2, 'Meters')], default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='targettype',
            constraint=models.UniqueConstraint(fields=('name', 'version', 'color'), name='unique_target_name_version_color'),
        ),
        migrations.AddField(
            model_name='stringpartime',
            name='firearm_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scoring.firearmtype'),
        ),
        migrations.AddField(
            model_name='stringpartime',
            name='string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.string'),
        ),
        migrations.AddField(
            model_name='stringdistance',
            name='string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.string'),
        ),
        migrations.AddField(
            model_name='drill',
            name='targets',
            field=models.ManyToManyField(to='scoring.targettype'),
        ),
        migrations.AlterField(
            model_name='firearm',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='scoring.firearmtype'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='stringpartime',
            constraint=models.UniqueConstraint(fields=('string', 'par', 'firearm_type', 'note'), name='unique_string_par_time'),
        ),
        migrations.AddConstraint(
            model_name='stringdistance',
            constraint=models.UniqueConstraint(fields=('string', 'distance', 'distance_type'), name='unique_string_distance'),
        ),
    ]
