# Generated by Django 4.2.3 on 2023-08-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0006_firearmtype_stringdistance_stringpartime_targettype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firearm',
            old_name='name',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='string',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='string',
            name='distance_type',
        ),
        migrations.RemoveField(
            model_name='string',
            name='long_gun_par_time',
        ),
        migrations.RemoveField(
            model_name='string',
            name='sidearm_par_time',
        ),
    ]
