# Generated by Django 4.2.3 on 2023-08-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0007_rename_name_firearm_model_remove_string_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='string',
            old_name='round_count',
            new_name='live_round_count',
        ),
        migrations.AddField(
            model_name='string',
            name='dummy_round_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
