# Generated by Django 4.2.3 on 2023-08-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0008_rename_round_count_string_live_round_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='string',
            name='dummy_round_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='string',
            name='live_round_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
