# Generated by Django 4.2.3 on 2023-08-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0010_remove_stringdistance_unique_string_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targettype',
            name='version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
