# Generated by Django 4.2.3 on 2023-08-04 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0011_alter_targettype_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringdistance',
            name='distance_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Yards'), (1, 'Feet'), (2, 'Meters')], default=0),
        ),
        migrations.AlterField(
            model_name='stringdistance',
            name='starting_distance',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='stringpartime',
            name='firearm_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='scoring.firearmtype'),
        ),
        migrations.AlterField(
            model_name='stringpartime',
            name='note',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='stringpartime',
            name='par',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='targettype',
            name='version',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
