# Generated by Django 4.2.3 on 2023-08-04 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0012_alter_stringdistance_distance_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stringpartime',
            name='unique_string_par_time',
        ),
        migrations.AlterField(
            model_name='drill',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shooter',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targettype',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targettype',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='target_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targettype',
            name='target_url_1',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targettype',
            name='target_url_2',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='targettype',
            name='target_url_3',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='stringpartime',
            constraint=models.UniqueConstraint(fields=('string', 'par', 'firearm_type'), name='unique_string_par_time'),
        ),
    ]
