# Generated by Django 4.2.3 on 2023-08-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0013_remove_stringpartime_unique_string_par_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stringpartime',
            name='unique_string_par_time',
        ),
        migrations.AlterField(
            model_name='stringpartime',
            name='firearm_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scoring.firearmtype'),
        ),
        migrations.AlterField(
            model_name='stringpartime',
            name='par',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddConstraint(
            model_name='stringpartime',
            constraint=models.UniqueConstraint(fields=('string', 'par', 'firearm_type'), name='unique_string_with_par_and_type'),
        ),
        migrations.AddConstraint(
            model_name='stringpartime',
            constraint=models.UniqueConstraint(condition=models.Q(('firearm_type', None)), fields=('string', 'par'), name='unique_string_with_par_and_no_type'),
        ),
        migrations.AddConstraint(
            model_name='stringpartime',
            constraint=models.UniqueConstraint(condition=models.Q(('par', None), ('firearm_type', None)), fields=('string',), name='unique_string_with_no_par_and_no_type'),
        ),
    ]
