# Generated by Django 4.2.3 on 2023-08-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0014_remove_stringpartime_unique_string_par_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringpartime',
            name='par',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
