# Generated by Django 4.2.3 on 2023-08-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0019_alter_firearm_manufacturer_alter_firearm_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stringpartime',
            constraint=models.UniqueConstraint(condition=models.Q(('par', None)), fields=('string', 'firearm_type'), name='unique_string_with_no_par_and_type'),
        ),
    ]
