# Generated by Django 4.2.3 on 2023-08-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0020_stringpartime_unique_string_with_no_par_and_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='firearm',
            name='caliber',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
