# Generated by Django 5.0.6 on 2024-07-04 20:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0021_firearm_caliber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, choices=[('CA', 'California'), ('CO', 'Colorado'), ('NV', 'Nevada'), ('UT', 'Utah')], max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5, null=True)),
                ('range_type', models.SmallIntegerField(choices=[(0, 'Indoor'), (1, 'Outdoor'), (2, 'Hybrid')], default=1)),
                ('temperature', models.SmallIntegerField(blank=True, null=True)),
                ('target_direction', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='history',
            name='drill',
        ),
        migrations.RemoveConstraint(
            model_name='stringdistance',
            name='unique_string_distance',
        ),
        migrations.RenameField(
            model_name='firearm',
            old_name='manufacturer',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='stringdistance',
            old_name='ending_distance',
            new_name='end_distance',
        ),
        migrations.RenameField(
            model_name='stringdistance',
            old_name='starting_distance',
            new_name='start_distance',
        ),
        migrations.RemoveField(
            model_name='score',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='score',
            name='from_concealment',
        ),
        migrations.RemoveField(
            model_name='score',
            name='penalties',
        ),
        migrations.RemoveField(
            model_name='score',
            name='points',
        ),
        migrations.RemoveField(
            model_name='score',
            name='score_time',
        ),
        migrations.AddField(
            model_name='drill',
            name='scored',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='barrel_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='sight_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='firearm',
            name='suppressed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='draw',
            field=models.CharField(blank=True, choices=[('Low-Ready', 'Low-Ready'), ('High-Ready', 'High-Ready'), ('Concealed', 'Concealed'), ('OWB', 'OWB')], max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='intermediary_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='pass_fail',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='point_penalty',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='time_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='total_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='ttfs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='shooter',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shooter',
            name='strong_hand',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='distance',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='generic_hits',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='mikes',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='zone_hits_1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='zone_hits_10',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='zone_hits_2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='zone_hits_3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='zone_hits_4',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='zone_hits_5',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='zone_hits_6',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='zone_hits_7',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='zone_hits_8',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='zone_hits_9',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='string',
            name='seqno',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='shooter',
            constraint=models.CheckConstraint(check=models.Q(('strong_hand', 'Left'), ('strong_hand', 'Right'), _connector='OR'), name='check_strong_hand'),
        ),
        migrations.AddConstraint(
            model_name='stringdistance',
            constraint=models.UniqueConstraint(fields=('string', 'start_distance', 'distance_type'), name='unique_string_distance'),
        ),
        migrations.AddField(
            model_name='score',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='scoring.event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
