# Generated by Django 5.0.6 on 2024-07-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0022_event_remove_history_drill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirearmDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sight_type', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Irons'), (1, 'Red Dot'), (2, 'Holographic'), (3, 'ACOG'), (4, 'LPVO'), (5, 'Rifle Scope'), (9, 'Other')], default=0)),
                ('suppressed', models.BooleanField(blank=True, null=True)),
                ('magazine_capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'firearm_details',
            },
        ),
        migrations.RenameModel(
            old_name='String',
            new_name='DrillString',
        ),
        migrations.RenameModel(
            old_name='StringDistance',
            new_name='DrillStringDistance',
        ),
        migrations.RenameModel(
            old_name='StringParTime',
            new_name='DrillStringPar',
        ),
        migrations.RenameField(
            model_name='firearm',
            old_name='make',
            new_name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='firearm',
            name='sight_type',
        ),
        migrations.RemoveField(
            model_name='firearm',
            name='suppressed',
        ),
        migrations.AddField(
            model_name='firearm',
            name='trigger_action',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Striker'), (1, 'Single-Action'), (2, 'Double-Action Only'), (3, 'Double-Action/Single-Action'), (4, 'Bolt'), (9, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='firearmtype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pistol'), (1, 'Rifle'), (2, 'Shotgun'), (3, 'Revolver'), (9, 'Other')]),
        ),
        migrations.AddField(
            model_name='firearm',
            name='firearm_details',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='scoring.firearmdetails'),
            preserve_default=False,
        ),
    ]
