# Generated by Django 5.0.7 on 2024-11-20 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0023_firearmdetails_rename_string_drillstring_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caliber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=64)),
                ('full_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caliber',
            },
        ),
        migrations.AlterField(
            model_name='firearmtype',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[('Pistol', 'Pistol'), ('Rifle', 'Rifle'), ('Shotgun', 'Shotgun'), ('Revolver', 'Revolver'), ('Other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='firearm',
            name='caliber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoring.caliber'),
        ),
        migrations.AddConstraint(
            model_name='firearm',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'model', 'caliber', 'barrel_length'), name='unique_manufacturer_model_caliber_barrel_length'),
        ),
    ]
