# Generated by Django 5.0.7 on 2024-11-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0024_caliber_alter_firearmtype_type_alter_firearm_caliber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firearmtype',
            name='type',
            field=models.CharField(choices=[('Pistol', 'Pistol'), ('Rifle', 'Rifle'), ('Shotgun', 'Shotgun'), ('Revolver', 'Revolver'), ('Other', 'Other')]),
        ),
    ]
