# Generated by Django 5.0.7 on 2024-11-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0025_alter_firearmtype_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caliber',
            constraint=models.UniqueConstraint(fields=('short_name',), name='unique_short_name_caliber'),
        ),
    ]
