# Generated by Django 5.0.7 on 2024-11-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0029_remove_firearm_unique_manufacturer_model_caliber_barrel_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firearm',
            name='model',
            field=models.CharField(max_length=128),
        ),
    ]
