"""Populates the database with the `Target` object data."""

__author__ = ['Joshua Schaeffer']
__version__ = '0.1.0'
__py_version__ = '3.10.6'
__creation_date__ = '2023-08-03'

import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'larissa.settings')

import django
django.setup()

from django.db.utils import IntegrityError
from scoring.models import TargetType

count = 0
added = 0
print('ADDING TARGETS TO DATABASE...')
targets = [
    {
        'name': '25M Alt-C',
        'description': '25 meter alternate course "c" target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/25m-alt-c/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/25M_AltC.png',
    },
    {
        'name': 'A-1000',
        'description': '1000″ rifle “A” target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-1000/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-1000.png',
    },
    {
        'name': 'A-1000',
        'description': '4-Bull 1000" rifle "A" target.',
        'version': '/4',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-1000-4/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-1000_4.jpg',
    },
    {
        'name': 'A-17',
        'description': 'Official NRA 50 ft. small bore rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-17/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-17.jpg',
    },
    {
        'name': 'A-17',
        'description': 'Official NRA 50 ft. small bore rifle target in orange.',
        'version': '',
        'color': 2,
        'target_url_1': 'https://www.nationaltarget.com/product/a-17-orange/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-17_Orange.jpg',
    },
    {
        'name': 'A-21',
        'description': 'Official NRA 200 yd. decimal small bore rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-21/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-21.jpg',
    },
    {
        'name': 'A-23',
        'description': 'Official NRA 50 yd. small bore rifle target.',
        'version': '/3',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-23-3/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-23_3.jpg',
    },
    {
        'name': 'A-23',
        'description': 'Official NRA 50 yd. small bore rifle target.',
        'version': '/5',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-23-5/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-23_5.jpg',
    },
    {
        'name': 'A-23',
        'description': 'Official NRA 50 yd. small bore rifle target.',
        'version': '/6',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-23-6/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-23_6.jpg',
    },
    {
        'name': 'A-25',
        'description': 'Official NRA 100 yd. small bore rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-25/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-25.jpg',
    },
    {
        'name': 'A-26',
        'description': 'Official NRA 50 meter small bore rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-26/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-26.jpg',
    },
    {
        'name': 'A-26',
        'description': 'Official NRA 50 meter small bore rifle target.',
        'version': '/6',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-26-6/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-26_6.png',
    },
    {
        'name': 'A-27',
        'description': 'Official NRA 50 yd. small bore rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-27/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-27.jpg',
    },
    {
        'name': 'A-27',
        'description': 'Official NRA 50 yd. small bore rifle target.',
        'version': '/6',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-27-6/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-27_6.jpg',
    },
    {
        'name': 'A-32',
        'description': 'Official NRA 50 ft. light rifile target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-32/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-32.jpg',
    },
    {
        'name': 'A-33',
        'description': 'NRA international 100 yd. small bore rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-33/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-33.jpg',
    },
    {
        'name': 'A-36',
        'description': 'NRA 50ft. rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-36/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-36.jpg',
    },
    {
        'name': 'A-37',
        'description': 'Official NRA 800 yd. mini-palma reduced to 100 yd. target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-36/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-37.jpg',
    },
    {
        'name': 'A-38',
        'description': 'Official NRA 900 yd. mini-palma reduced to 100 yd. target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-38/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-38.jpg',
    },
    {
        'name': 'A-39',
        'description': 'Official NRA 1000 yd. mini-palma reduced to 100 yd. target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-39/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-39.jpg',
    },
    {
        'name': 'A-50',
        'description': 'NRA 50 meter UIT small bore rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-50/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-50.jpg',
    },
    {
        'name': 'A-51',
        'description': 'NRA 50 yd. UIT small bore rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-51/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-51.jpg',
    },
    {
        'name': 'A-7',
        'description': 'Official 75 ft. small bore rifle target.',
        'version': '/5',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-7-5/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A-7_5.jpg',
    },
    {
        'name': 'A.1',
        'description': 'Reactive fire stance life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.1.png',
    },
    {
        'name': 'A.2',
        'description': 'Two handed grip stance life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-2/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.2.png',
    },
    {
        'name': 'A.3',
        'description': 'Automatic weapon stance life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-3/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.3.png',
    },
    {
        'name': 'A.4',
        'description': 'Hostage life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-4/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.4.png',
    },
    {
        'name': 'A.5',
        'description': 'Armored stance life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-5/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.5.png',
    },
    {
        'name': 'A.6',
        'description': 'Single stance (CRM) life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-6/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.6.png',
    },
    {
        'name': 'A.7',
        'description': 'Dog attacking life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-7/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.7.png',
    },
    {
        'name': 'A.8',
        'description': 'Single stance (CRM) life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-8/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.8.png',
    },
    {
        'name': 'A.9',
        'description': 'Double high/low stances life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-9/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.9.png',
    },
    {
        'name': 'A.10',
        'description': 'Single stance (CVM) life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-10/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.10.png',
    },
    {
        'name': 'A.11',
        'description': 'Under car position life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/a-11/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/A.11.png',
    },
    {
        'name': 'AP-1',
        'description': 'Modified D-1 target.',
        'version': 'CB (cardboard)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ap-1cb/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/AP-1_CB.jpg',
    },
    {
        'name': 'AP-1',
        'description': 'Modified D-1 target.',
        'version': 'P (paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ap-1p/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/AP-1_P.jpg',
    },
    {
        'name': 'AP-1',
        'description': 'Modified D-1 target.',
        'version': 'T (heavy paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ap-1t/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/AP-1_T.jpg',
    },
    {
        'name': 'AP-2',
        'description': 'Reduced from AP-1.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ap-2/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/AP-2.jpg',
    },
    {
        'name': 'AR-1',
        'description': "America's rifle target.",
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ar-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/AR-1.jpg',
    },
    {
        'name': 'AR-1',
        'description': "America's rifle target.",
        'version': 'CB (cardboard)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ar-1-cb/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/AR-1_CB.jpg',
    },
    {
        'name': 'AR-2',
        'description': 'Rife target for 7 to 100 yd. with multiple scoring zones and different impact areas with 2 sight pictures.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ar-2/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/AR-2.jpg',
    },
    {
        'name': 'AR-2',
        'description': 'Rife target for 7 to 100 yd. with multiple scoring zones and different impact areas with 2 sight pictures.',
        'version': 'CB (cardboard)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ar-2-cb/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/AR-2_CB.jpg',
    },
    {
        'name': 'B-2',
        'description': 'Official NRA 50 ft. slow fire pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-2/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-2.jpg',
    },
    {
        'name': 'B-2',
        'description': 'Official NRA 50 ft. slow fire pistol target.',
        'version': 'RC (red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-2-rc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-2_RC.jpg',
    },
    {
        'name': 'B-2',
        'description': 'Official NRA 50 ft. slow fire pistol target (2).',
        'version': '/2(P) (paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-2-2p/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': '',
    },
    {
        'name': 'B-11',
        'description': 'NRA 50 ft. slow fire pistol target reduced from 50 meter B-17.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-11/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': '',
    },
    {
        'name': 'B-16',
        'description': 'Official NRA 25 yd. slow fire pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-16/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-16.jpg',
    },
    {
        'name': 'B-16',
        'description': 'Official NRA 25 yd. slow fire pistol target.',
        'version': 'RC (red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-16rc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-16_RC.jpg',
    },
    {
        'name': 'B-16',
        'description': 'Official NRA 25 yd. slow fire pistol target in high visability green.',
        'version': '',
        'color': 4,
        'target_url_1': 'https://www.nationaltarget.com/product/b-16-hv-green/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-16_Green.jpg',
    },
    {
        'name': 'B-16',
        'description': 'Official NRA 25 yd. slow fire pistol target in high visability green.',
        'version': '',
        'color': 2,
        'target_url_1': 'https://www.nationaltarget.com/product/b-16-orange/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-16_Orange.jpg',
    },
    {
        'name': 'B-17',
        'description': '25/50 meter UIT pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-17/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-17.jpg',
    },
    {
        'name': 'B-19',
        'description': '25/50 yd. pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-19/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-19.jpg',
    },
    {
        'name': 'B-21',
        'description': '50 Yard "Kill & Disable" scoring target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-21/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': '',
    },
    {
        'name': 'B-21',
        'description': '25 yd. reduced from 50 yd. B-21 target.',
        'version': 'E (economy)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-21e/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-21_E.jpg',
    },
    {
        'name': 'B-21',
        'description': '25 yd. reduced from 50 yd. B-21 target in blue.',
        'version': 'E (economy)',
        'color': 3,
        'target_url_1': 'https://www.nationaltarget.com/product/b-21e-fl/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': '',
    },
    {
        'name': 'B-21',
        'description': '25 yd. reduced from 50 yd. B-21 target in high visibility green.',
        'version': 'E (economy)',
        'color': 4,
        'target_url_1': 'https://www.nationaltarget.com/product/b-21e-hv-green/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-21_E_Green.jpg',
    },
    {
        'name': 'B-22',
        'description': 'Official NRA 25 yd. slow and timed fire and 15 yd. rapid fire Army "L" target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-22/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-22.jpg',
    },
    {
        'name': 'B-27',
        'description': '50 yd. police pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27.jpg',
    },
    {
        'name': 'B-27',
        'description': '50 yd. police pistol target printed in blue.',
        'version': '',
        'color': 3,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27-blue/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_Blue.jpg',
    },
    {
        'name': 'B-27',
        'description': '50 yd. police pistol target printed in orange',
        'version': '',
        'color': 2,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27-orange/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_Orange.jpg',
    },
    {
        'name': 'B-27',
        'description': '24" 50 yd. police pistol target.',
        'version': '24"',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27-24/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_24.jpg',
    },
    {
        'name': 'B-27',
        'description': '24" 50 yd. police pistol target.',
        'version': '24" CB (cardboard)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-2724-cb/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_24CB.jpg',
    },
    {
        'name': 'B-27',
        'description': '24" 50 yd. police pistol target.',
        'version': 'RC (red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-2724-rc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_24RC.jpg',
    },
    {
        'name': 'B-27',
        'description': '24" 50 yd. police pistol target.',
        'version': 'REV (reversed)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-2724-rev/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_24REV.jpg',
    },
    {
        'name': 'B-27',
        'description': '24" 50 yd. police pistol target.',
        'version': 'REVRC (reversed red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-2724-revrc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_24REVRC.jpg',
    },
    {
        'name': 'B-27',
        'description': '50 yd. police pistol target, economy version.',
        'version': 'E (economy)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27e/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_E.jpg',
    },
    {
        'name': 'B-27',
        'description': '50 yd. police pistol target printed in blue, economy version.',
        'version': 'E (economy)',
        'color': 3,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27e-blue/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_E_Blue.jpg',
    },
    {
        'name': 'B-27',
        'description': '50 yd. police pistol target printed in orange, economy version.',
        'version': 'E (economy)',
        'color': 2,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27e-orange/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_E_Orange.jpg',
    },
    {
        'name': 'B-27',
        'description': '50 yd. police pistol target printed in high visibility green, economy version.',
        'version': 'E (economy)',
        'color': 4,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27e-hv-green/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_E_Green.jpg',
    },
    {
        'name': 'B-27',
        'description': '50 yd. police pistol target, economy version.',
        'version': 'ERC (economy red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27e-rc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': '',
    },
    {
        'name': 'B-27',
        'description': '50 yd. police pistol target, economy version.',
        'version': 'EREV (economy reversed)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27e-rev/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': '',
    },
    {
        'name': 'B-27',
        'description': '50 yd. police pistol target, economy version.',
        'version': 'EREVRC (economy reversed red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-27e-revrc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-27_EREVRC.gif',
    },
    {
        'name': 'B-29',
        'description': '50 ft. police pistol target reduced from the 50 yd. B-27.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-29/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-29.jpg',
    },
    {
        'name': 'B-29',
        'description': '50 ft. police pistol target reduced from the 50 yd. B-27 printed in blue.',
        'version': '',
        'color': 3,
        'target_url_1': 'https://www.nationaltarget.com/product/b-29-blue/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-29_Blue.jpg',
    },
    {
        'name': 'B-29',
        'description': '50 ft. police pistol target reduced from the 50 yd. B-27 printed in high visibility green.',
        'version': '',
        'color': 4,
        'target_url_1': 'https://www.nationaltarget.com/product/b-29-hv-green/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-29_Green.jpg',
    },
    {
        'name': 'B-29',
        'description': '50 ft. police pistol target reduced from the 50 yd. B-27 printed in orange.',
        'version': '',
        'color': 2,
        'target_url_1': 'https://www.nationaltarget.com/product/b-29-orange/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-29_Orange.jgp',
    },
    {
        'name': 'B-29',
        'description': '50 ft. police pistol target with red center reduced from the 50 yd. B-27.',
        'version': 'RC (red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-29-rc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-29_RC.jpg',
    },
    {
        'name': 'B-29',
        'description': '50 ft. police pistol target reduced from the 50 yd. B-27.',
        'version': 'REVRC (reversed red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-29-revrc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-29_REVRC.jgp',
    },
    {
        'name': 'B-3',
        'description': 'Official NRA 50 ft. timed and rapbid fire pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-3/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-3.jpg',
    },
    {
        'name': 'B-3',
        'description': 'Official NRA 50 ft. timed and rapid fire pistol target.',
        'version': 'RC (red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-3-rc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-3_RC.jpg',
    },
    {
        'name': 'B-33',
        'description': '50 ft. international center fire and standard pistol reduced from 25 meters.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-33/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-33.jpg',
    },
    {
        'name': 'B-34',
        'description': '24 yd. police pistol target reduced from the 50 yd. B-27.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-34/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-34.jpg',
    },
    {
        'name': 'B-34',
        'description': '25 yd. police pistol target reduced from the 50 yd. B-27 printed in blue.',
        'version': '',
        'color': 3,
        'target_url_1': 'https://www.nationaltarget.com/product/b-34-blue/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-34_Blue.jpg',
    },
    {
        'name': 'B-34',
        'description': '25 yd. police pistol target reduced from the 50 yd. B-27 printed in high visibility green.',
        'version': '',
        'color': 4,
        'target_url_1': 'https://www.nationaltarget.com/product/b-34-hv-green/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-34_Green.jpg',
    },
    {
        'name': 'B-34',
        'description': '25 yd. police pistol target reduced from the 50 yd. B-27 printed in orange.',
        'version': '',
        'color': 2,
        'target_url_1': 'https://www.nationaltarget.com/product/b-34-orange/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-34_Orange.jpg',
    },
    {
        'name': 'B-34',
        'description': '25 yd. reversed police pistol target reduced from the 50 yd. B-27.',
        'version': 'REV (reversed)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-34-rev/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-34_REV.jpg',
    },
    {
        'name': 'B-34',
        'description': '25 yd. reversed with red center police pistol target reduced from the 50 yd. B-27.',
        'version': 'REVRC (reversed red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-34-revrc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-34_REVRC',
    },
    {
        'name': 'B-34',
        'description': '25 yd. with red center police pistol target reduced from the 50 yd. B-27.',
        'version': 'RC (red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-34rc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-34_RC.jpg',
    },
    {
        'name': 'B-35',
        'description': '25 yd. free pistol target reduced from the 50 meter B-17.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-35/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': '',
    },
    {
        'name': 'B-37',
        'description': '25 meter rapid fire UIT target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-37/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-37.jpg',
    },
    {
        'name': 'B-38',
        'description': '25 yd. rapid fire UIT target reduced from the 25 meter B-37.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-38/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-38.jpg',
    },
    {
        'name': 'B-39',
        'description': '50 ft. rapid fire UIT target reduced from the 25 meter B-37.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-39/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-39.jpg',
    },
    {
        'name': 'B-4',
        'description': 'Official NRA 20 yd. slow fire pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-4/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-4.jpg',
    },
    {
        'name': 'B-5',
        'description': 'Official NRA 20 yd. timed and rapid fire pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-5/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-5.jpg',
    },
    {
        'name': 'B-6',
        'description': 'Official NRA 50 yd. slow fire pistol target.',
        'version': 'P (paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-6p/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-6_P.jpg',
    },
    {
        'name': 'B-6',
        'description': 'Official NRA 50 yd. slow fire pistol target.',
        'version': 'T (heavy paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-6t/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-6_T.jpg',
    },
    {
        'name': 'B-8',
        'description': 'Official NRA 25 yd. timed and rapid fire paper target.',
        'version': 'P (paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-8p/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-8_P.jpg',
    },
    {
        'name': 'B-8',
        'description': 'Official NRA 25 yd. timed and rapid fire paper with red center target.',
        'version': 'PRC (paper red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-8prc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-8_PRC.jpg',
    },
    {
        'name': 'B-8',
        'description': 'Official NRA 25 yd. timed and rapid fire heavy paper target.',
        'version': 'T (heavy paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/b-8t/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/B-8_T.jpg',
    },
    {
        'name': 'BT-1',
        'description': 'Drawn man in shades of blue target.',
        'version': '',
        'color': 3,
        'target_url_1': 'https://www.nationaltarget.com/product/bt-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/BT-1_Blue.gif',
    },
    {
        'name': 'BT-1',
        'description': 'Drawn man in shades of blue target reduced.',
        'version': 'R (reduced)',
        'color': 3,
        'target_url_1': 'https://www.nationaltarget.com/product/bt-1r/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/BT-1_R_Blue.gif',
    },
    {
        'name': 'C-1',
        'description': '300 meter UIT target without 1 & 2 rings.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/c-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/C-1.gif',
    },
    {
        'name': 'C-2',
        'description': '200 yd. UIT target reduced from 300 meter C-1.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/c-2/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/C-2.gif',
    },
    {
        'name': 'D-1',
        'description': 'Official NRA Bianchi cup target.',
        'version': 'CB (cardboard)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/d-1cb/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/D-1_CB.jpg',
    },
    {
        'name': 'D-1',
        'description': 'Official NRA Bianchi cup paper target.',
        'version': 'P (paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/d-1p/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/D-1_P.jpg',
    },
    {
        'name': 'D-1',
        'description': 'Official NRA Bianchi cup heavy paper target.',
        'version': 'T (heavy paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/d-1t/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/D-1_T.jpg',
    },
    {
        'name': 'DS-Q1A',
        'description': 'Drawn man in shades of balck target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ds-q1a/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/DS-Q1A.jpg',
    },
    {
        'name': 'DT-2A',
        'description': 'Discretionary 4 color custom target for command training.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://shop.actiontarget.com/content/dt-2a-discretionary-command-training-target-version-2-a.asp',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/DT-2A.jpg',
    },
    {
        'name': 'DT-2B',
        'description': 'Discretionary 4 color custom target for command training.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://shop.actiontarget.com/content/dt-2b-discretionary-command-training-target-version-2-b.asp',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/DT-2B.jpg',
    },
    {
        'name': 'DT-2C',
        'description': 'Discretionary 4 color custom target for command training.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://shop.actiontarget.com/content/dt-2c-discretionary-command-training-target-version-2-c.asp',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/DT-2C.jpg',
    },
    {
        'name': 'DT-3',
        'description': 'Discretionary 4 color custom target for command training.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/dt-3/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/DT-3.png',
    },
    {
        'name': 'F-37',
        'description': 'Official NRA 800 yard mini-palma target reduced to 100 yards for F-class.',
        'version': 'F-class',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/f-37-f-class/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/F-37_Fclass.jpg',
    },
    {
        'name': 'F-38',
        'description': 'Official NRA 900 yard mini-palma target reduced to 100 yards for F-class.',
        'version': 'F-class',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/f-38-f-class/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/F-38_Fclass.jpg',
    },
    {
        'name': 'F-39',
        'description': 'Official NRA 1000 yard mini-palma target reduced to 100 yards for F-class.',
        'version': 'F-class',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/f-39-f-class/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/F-39_Fclass.jpg',
    },
    {
        'name': 'F2S CT-4.12',
        'description': 'Skill builder training target designed for both carbine and pistol training with dual bullseyes.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/f2s-ct-4-12/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/F2SCT-4.12.png',
    },
    {
        'name': 'FBI-Q',
        'description': 'Center mass silhouette 2 tone gray target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/fbi-q/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/FBI-Q.gif',
    },
    {
        'name': 'FBI-Q',
        'description': 'Center mass silhouette 2 tone gray target.',
        'version': 'R (reversed)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/fbi-q-reverse/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/FBI-Q_R.gif',
    },
    {
        'name': 'GA-PT',
        'description': 'GA state qualifying target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ga-pt/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/GA-PT.gif',
    },
    {
        'name': 'Green Ops',
        'description': 'Official Green Ops target. 2 color target with 7 numbered white rectangles in dark green and black',
        'version': '',
        'color': 4,
        'target_url_1': 'https://www.nationaltarget.com/product/green-ops-target/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/GreenOps.jpg',
    },
    {
        'name': 'GreyBeard Actual',
        'description': 'Official GreyBeard Actual target printed on lightweight buff paper.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/greybeard-actual-target/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/GreyBeardActual.jpg',
    },
    {
        'name': 'IALEFI-Q',
        'description': 'Official International Association of Law Enforcement Firearms Instructors target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ialefi-q/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IALEFI-Q.gif',
    },
    {
        'name': 'IBS 100 YD',
        'description': 'International Benchrest Shooters 100 yd. bench rest target.',
        'version': 'BR (bench rest)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ibs-100-yd-br/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IBS100YD_BR.jpg',
    },
    {
        'name': 'IBS 100 YD',
        'description': 'International Benchrest Shooters 100 yd. hunter rifle target.',
        'version': 'HR (hunter rifile)',
        'color': 5,
        'target_url_1': 'https://www.nationaltarget.com/product/ibs-100-yd-hr/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IBS100YD_HR_Red.png',
    },
    {
        'name': 'IBS 1000 YD',
        'description': 'International Benchrest Shooters 1000 yd. bench rest target.',
        'version': 'BR (bench rest)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ibs-1000-yd-br/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IBS1000YD_BR.jpg',
    },
    {
        'name': 'IBS 200 YD',
        'description': 'International Benchrest Shooters 200 yd. bench rest target.',
        'version': 'BR (bench rest)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ibs-200-yd-br/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IBS200YD_BR.jpg',
    },
    {
        'name': 'IBS 200 YD',
        'description': 'International Benchrest Shooters 200 yd. hunter rifle target.',
        'version': 'HR (hunter rifle)',
        'color': 5,
        'target_url_1': 'https://www.nationaltarget.com/product/ibs-200-yd-hr/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IBS200YD_HR_Red.gif',
    },
    {
        'name': 'IBS 300 YD',
        'description': 'International Benchrest Shooters 300 yd. bench rest target.',
        'version': 'BR (bench rest)',
        'color': 5,
        'target_url_1': 'https://www.nationaltarget.com/product/ibs-300-yd-br/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IBS300YD_BR_Red.jpg',
    },
    {
        'name': 'IBS 300 YD',
        'description': 'International Benchrest Shooters 300 yd. hunter rifle target.',
        'version': 'HR (hunter rifle)',
        'color': 5,
        'target_url_1': 'https://www.nationaltarget.com/product/ibs-300-yd-hr/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IBS300YD_HR_Red.jpg',
    },
    {
        'name': 'IBS 50 YD',
        'description': 'International Benchrest Shooters 50 yd. rimfire target.',
        'version': 'RF (rimfire)',
        'color': 4,
        'target_url_1': 'https://www.nationaltarget.com/product/ibs-50-yd-rf/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IBS50YD_RF_Green.jpg',
    },
    {
        'name': 'IBS 600 YD',
        'description': 'International Benchrest Shooters 600 yd. bench rest target.',
        'version': 'BR (bench rest)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ibs-600-yd-br/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IBS600YD_BR.gif',
    },
    {
        'name': 'ICE-QT',
        'description': 'Immigration Control Enforcement qualifying target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ice-qt/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/ICE-QT.png',
    },
    {
        'name': 'ICE-QT',
        'description': 'Immigration Control Enforcement qualifying mindset target.',
        'version': 'MS (mind set)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ice-qtms/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/ICE-QT_MS.jpg',
    },
    {
        'name': 'IDPA',
        'description': 'Official International Defensive Pistol Association cardboard practice target.',
        'version': 'CB (cardboard)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/idpa-cb/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IDPA_CB.jpg',
    },
    {
        'name': 'IDPA',
        'description': 'Official International Defensive Pistol Association paper practice target.',
        'version': 'P (paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/idpap/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IDPA_P.jpg',
    },
    {
        'name': 'IDPA',
        'description': 'Official International Defensive Pistol Association cardboard practice target.',
        'version': 'Steel',
        'color': 0,
        'target_url_1': '',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IDPA_S.jpg',
    },
    {
        'name': 'INDEX-CIT',
        'description': 'Hostile man with head, center mass, pelvic area scoring to include vital organs and spinal column.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/index-cit/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/INDEX-CIT.jpg',
    },
    {
        'name': 'IPSC',
        'description': 'Official International Practice Shooting Confederation cardboard practice target.',
        'version': 'CB (cardboard)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ipsc-cb/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IPSC_CB.jpg',
    },
    {
        'name': 'IPSC',
        'description': 'Official International Practice Shooting Confederation paper practice target.',
        'version': 'P (paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ipsc-p/',
        'target_url_2': 'https://shop.actiontarget.com/content/ipsc-p-ipsc-uspsa-paper-target.asp',
        'target_url_3': '',
        'picture': 'target_images/IPSC_P.jpg',
    },
    {
        'name': 'IPSC',
        'description': 'Official International Practice Shooting Confederation paper practice target.',
        'version': 'Steel',
        'color': 0,
        'target_url_1': '',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/IPSC_S.jpg',
    },
    {
        'name': 'JDC DOMINO',
        'description': 'Justified Defensive Concepts domino target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/jdc-domino/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/JDC-DOMINO.png',
    },
    {
        'name': 'JDC MODULATION',
        'description': 'Justified Defensive Concepts modulation target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/jdc-modulation/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/JDC-MOD.png',
    },
    {
        'name': 'JDC-1',
        'description': 'Justified Defensive Concepts multi-use training target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/jdc-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/JDC-1.jpg',
    },
    {
        'name': 'JDC-2A',
        'description': 'Justified Defensive Concepts custom training target with 6 circles and diamond, club, heart, and spade.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/jdc-2a/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/JDC-2A.jpg',
    },
    {
        'name': 'JDC-2B',
        'description': 'Justified Defensive Concepts custom training target with 6 circles and diamond, club, heart, and spade.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/jdc-2b/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/JDC-2B.jpg',
    },
    {
        'name': 'JDC-3',
        'description': 'Justified Defensive Concepts custom precision zero target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/jdc-3/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/JDC-3.jpg',
    },
    {
        'name': 'JDC-4',
        'description': 'Justified Defensive Concepts custom training target with diamon, club, heart, and spade.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/jdc-4/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/JDC-4.jpg',
    },
    {
        'name': 'JDC-8',
        'description': 'Justified Defensive Concepts custom training target with diamon, club, heart, and spade.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/jdc-8/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/JDC-8.jpg',
    },
    {
        'name': 'LTT-1',
        'description': 'The Langdon Tactical pistol skills target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ltt-1-2/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/LTT-1.jpg',
    },
    {
        'name': 'LR-S',
        'description': '100 yd. mini-palma target reduced for 800, 900, and 1000 yd.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/mini-palma-lr-s/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/LR-S.png',
    },
    {
        'name': 'MPPC',
        'description': 'Hostile man target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/mppc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/MPPC.gif',
    },
    {
        'name': 'MR',
        'description': 'NRA 500 yd. high power rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/mr/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/MR.jpg',
    },
    {
        'name': 'MR-1',
        'description': 'NRA 600 yd. high power rifle slow fire target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/mr-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/MR-1.jpg',
    },
    {
        'name': 'MR-31',
        'description': 'NRA 100 yd. high power rifle slow fire target reduced from the 600 yd. MR-1.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/mr-31/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/MR-31.jpg',
    },
    {
        'name': 'MR-52',
        'description': 'NRA 200 yd. high power rifle slow fire target reduced from the 600 yd. MR-1.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/mr-52/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/MR-52.jpg',
    },
    {
        'name': 'MR-63',
        'description': 'NRA 300 yd. high power rifle slow fire target reduced from the 600 yd. MR-1.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/mr-63/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/MR-63.jpg',
    },
    {
        'name': 'MR-65',
        'description': 'NRA 500 yd. full face target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/mr-65/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/MR-65.jpg',
    },
    {
        'name': 'MR-65',
        'description': 'NRA 500 yd. full face target for F-class.',
        'version': 'F-class',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/mr-65-f-class/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/MR-65_Fclass.jpg',
    },
    {
        'name': 'MSP Training',
        'description': 'Official Modern Samurai Project training target',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/msp-training-target/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/MSPTraining.jpg',
    },
    {
        'name': 'NLEFIA-V2',
        'description': 'Official National Law Enforcement Firearms Instructors Association target based on the TQ-21 design.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/nlefia-v2/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NLEFIA-V2.png',
    },
    {
        'name': 'NTC-100',
        'description': 'Woman with gun target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-100/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-100.gif',
    },
    {
        'name': 'NTC-101',
        'description': 'Man with shotgun target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-101/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-101.gif',
    },
    {
        'name': 'NTC-102',
        'description': 'Woman with gun and badge target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-102/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-102.gif',
    },
    {
        'name': 'NTC-103',
        'description': 'Older man with gun target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-103/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-103.gif',
    },
    {
        'name': 'NTC-104',
        'description': 'Younger man with gun target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-104/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-104.gif',
    },
    {
        'name': 'NTC-105',
        'description': 'Man with gun target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-105/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-105.gif',
    },
    {
        'name': 'NTC-106',
        'description': 'Man with gun target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-106/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-106.gif',
    },
    {
        'name': 'NTC-107',
        'description': 'Woman in car with gun target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-107/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-107.gif',
    },
    {
        'name': 'NTC-108',
        'description': 'Man with gun in dark background target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-108/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-108.gif',
    },
    {
        'name': 'NTC-109',
        'description': 'Man with gun in light background target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-109/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-109.gif',
    },
    {
        'name': 'NTC-200',
        'description': 'Older man with umbrella target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-200/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-200.gif',
    },
    {
        'name': 'NTC-201',
        'description': 'Younger man with wrench target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-201/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-201.gif',
    },
    {
        'name': 'NTC-205',
        'description': 'Man with gun and badge target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-205/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-205.gif',
    },
    {
        'name': 'NTC-206',
        'description': 'Man with gun and badge target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-206/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-206.gif',
    },
    {
        'name': 'NTC-208',
        'description': 'Man with gun and badge in dark background target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-208/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-208.gif',
    },
    {
        'name': 'NTC-209',
        'description': 'Man with gun and badge in light background target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-209/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-209.gif',
    },
    {
        'name': 'NTC-300',
        'description': 'Hooded man with gun with FBI-Q scoring target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-300/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-300.gif',
    },
    {
        'name': 'NTC-301',
        'description': 'Hooded man with gun with TQ-19 scoring target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-301/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-301.gif',
    },
    {
        'name': 'NTC-302',
        'description': 'Hooded man with gun target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-302/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-302.gif',
    },
    {
        'name': 'NTC-303',
        'description': 'Man with gun and hostage target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-303/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-303.gif',
    },
    {
        'name': 'NTC-500',
        'description': 'Man with gun colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-500/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-500.gif',
    },
    {
        'name': 'NTC-505',
        'description': 'Man with gun colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-505/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-505.gif',
    },
    {
        'name': 'NTC-510',
        'description': 'Man with shotgun colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-510/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-510.gif',
    },
    {
        'name': 'NTC-515',
        'description': 'Man with gun and hostage colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-515/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-515.gif',
    },
    {
        'name': 'NTC-520',
        'description': 'Man with shotgun colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-520/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-520.gif',
    },
    {
        'name': 'NTC-525',
        'description': 'Hooded man with gun with B-27 scoring colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-525/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-525.gif',
    },
    {
        'name': 'NTC-530',
        'description': 'Woman with gun colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-530/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-530.gif',
    },
    {
        'name': 'NTC-535',
        'description': 'Shirtless young man with gun colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-535/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-535.gif',
    },
    {
        'name': 'NTC-540',
        'description': 'Man with gun with vitals scoring colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-540/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-540.gif',
    },
    {
        'name': 'NTC-545',
        'description': 'Man in door with gun with TQ-19 scoring colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-545/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-545.gif',
    },
    {
        'name': 'NTC-550',
        'description': 'Young man with gun colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-550/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-550.gif',
    },
    {
        'name': 'NTC-555',
        'description': 'Man with gun side view with vitals scoring colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntc-555/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTC-555.gif',
    },
    {
        'name': 'NTZ-600',
        'description': 'Zombie man colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntz-600/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTZ-600.gif',
    },
    {
        'name': 'NTZ-605',
        'description': 'Zombie man colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntz-605/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTZ-605.gif',
    },
    {
        'name': 'NTZ-610',
        'description': 'Zombie solider colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntz-610/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTZ-610.gif',
    },
    {
        'name': 'NTZ-615',
        'description': 'Zombie attacking woman colored target.',
        'version': '',
        'color': 9,
        'target_url_1': 'https://www.nationaltarget.com/product/ntz-615/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/NTZ-615.gif',
    },
    {
        'name': 'P-1',
        'description': '2009 LA state qualifying target in green.',
        'version': '',
        'color': 4,
        'target_url_1': 'https://www.nationaltarget.com/product/p-1-post-target-2009/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/P-1_Green.gif',
    },
    {
        'name': 'Poker',
        'description': '50 ft. deck of cards poker target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/poker-target/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/Poker.gif',
    },
    {
        'name': 'SR-21',
        'description': 'NRA 100 yd. high powered rifle rapid fire target reduced from the 300 yd. SR-3.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/sr-21/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/SR-21.jpg',
    },
    {
        'name': 'SR-42',
        'description': 'NRA 200 yd. high powered rifle rapid fire target reduced from the 300 yd. SR-3.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/sr-42/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/SR-42.jpg',
    },
    {
        'name': 'ST-1',
        'description': 'Sighting target for M-1 Rifles using M-72 match ammunition.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/st-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': '',
    },
    {
        'name': 'ST-2',
        'description': 'NRA 40 yd. shotgun sighting target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/st-2/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/ST-2.gif',
    },
    {
        'name': 'ST-3',
        'description': '100 yd. rifle sighting target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/st-3/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/ST-3.gif',
    },
    {
        'name': 'ST-3',
        'description': '100 yd. rifle sighting target in orange.',
        'version': '',
        'color': 2,
        'target_url_1': 'https://www.nationaltarget.com/product/st-3-orange/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/ST-3_Orange.jpg',
    },
    {
        'name': 'ST-3',
        'description': '100 yd. rifle sighting target in red.',
        'version': '',
        'color': 5,
        'target_url_1': 'https://www.nationaltarget.com/product/st-3-red/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/ST-3_Red.jpg',
    },
    {
        'name': 'ST-3',
        'description': '100 yd. rifle sighting with red center target.',
        'version': 'RC (red center)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/st-3rc/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/ST-3_RC.gif',
    },
    {
        'name': 'ST-4',
        'description': '100 yd. rifle sighting target in red.',
        'version': '',
        'color': 5,
        'target_url_1': 'https://www.nationaltarget.com/product/st-4/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/ST-4_Red.gif',
    },
    {
        'name': 'TQ-1',
        'description': 'Official NRA 50 ft. rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-1-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-1.jpg',
    },
    {
        'name': 'TQ-1',
        'description': 'Official NRA 50 ft. rifle target.',
        'version': '/5',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-1-5/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-1_5.jpg',
    },
    {
        'name': 'TQ-12',
        'description': 'NRA 50 ft. pistol silhouette of chicken and pig target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-12/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-12.jpg',
    },
    {
        'name': 'TQ-13',
        'description': 'NRA 50 ft. pistol silhouette of turkey and ram target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-13/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-13.jpg',
    },
    {
        'name': 'TQ-14',
        'description': 'NRA 50 ft. rifle silhouette of chicken, pig, turkey, and ram target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-14/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-14.jpg',
    },
    {
        'name': 'TQ-15',
        'description': '',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-15/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-15.gif',
    },
    {
        'name': 'PT-1',
        'description': '15 ft. paper plate target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/pt-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/PT-1.jpg',
    },
    {
        'name': 'Q-PT',
        'description': 'Pistol training custom "Q" target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/q-pt/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/Q-PT.jpg',
    },
    {
        'name': 'Pistol Dot Torture',
        'description': 'Pistol dot torture target.',
        'version': '',
        'color': 0,
        'target_url_1': '',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/PistolDotTorture.png',
    },
    {
        'name': 'Rifle Dot Torture',
        'description': 'Rifle dot torture target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/rifle-dot-torture/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/RifleDotTorture.jpg',
    },
    {
        'name': 'S.1',
        'description': 'Kneeling sniper life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/s-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/S.1.png',
    },
    {
        'name': 'S.2',
        'description': 'Heat mirage sniper life-size tactical anatomy target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/s-2/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/S.2.png',
    },
    {
        'name': 'SR',
        'description': 'Standard 200 yd. rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/sr/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/SR.jpg',
    },
    {
        'name': 'SR-1',
        'description': 'Official NRA 100 yd. military type target reduced from the 200 yd. SR.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/sr-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/SR-1.jpg',
    },
    {
        'name': 'TT302H-J',
        'description': 'Target Telemetrics targets.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tt302h-j/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TT302H-J.jpg',
    },
    {
        'name': 'USA/NRA 50',
        'description': '',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/usa-nra-50/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/USA-NRA-50.jpg',
    },
    {
        'name': 'TQ-16',
        'description': '50 ft. target reduced from the 25 yd. TQ-15.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-16/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-16.gif',
    },
    {
        'name': 'TQ-19',
        'description': '',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-19/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-19.gif',
    },
    {
        'name': 'TQ-2',
        'description': 'Official NRA 75 ft. small bore rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-2/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-2.jpg',
    },
    {
        'name': 'TQ-20',
        'description': 'Reduced from the TQ-19.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-20/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-20.gif',
    },
    {
        'name': 'TQ-21',
        'description': '',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-21/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-21.gif',
    },
    {
        'name': 'TQ-22',
        'description': 'Reduced from the TQ-21.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-22/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-22.gif',
    },
    {
        'name': 'TQ-3',
        'description': 'Official NRA 50 yd. small bore rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-3-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-3_1.jpg',
    },
    {
        'name': 'TQ-3',
        'description': 'Official NRA 50 yd. small bore rifle paper target.',
        'version': '/2P (paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-3-2p/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-3_2P.jpg',
    },
    {
        'name': 'TQ-3',
        'description': 'Official NRA 50 yd. small bore rifle heavy paper target.',
        'version': '/2T (heavy paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-3-2t/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-3_2T.jpg',
    },
    {
        'name': 'TQ-3',
        'description': 'Official NRA 50 yd. small bore rifle target.',
        'version': '/5',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-3-5/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-3_5.jpg',
    },
    {
        'name': 'TQ-3',
        'description': 'Official NRA 50 yd. small bore rifle target in orange.',
        'version': '/5',
        'color': 2,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-3-5-orange/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-3_5_Orange.jpg',
    },
    {
        'name': 'TQ-4',
        'description': 'Official NRA 100 yd. small bore rifle paper target.',
        'version': 'P (paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-36/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-4_P.jpg',
    },
    {
        'name': 'TQ-4',
        'description': 'Official NRA 100 yd. small bore rifle paper target in blue.',
        'version': 'P (paper)',
        'color': 3,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-4p-blue/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-4_P_Blue.jpg',
    },
    {
        'name': 'TQ-4',
        'description': 'Official NRA 100 yd. small bore rifle paper target in orange.',
        'version': 'P (paper)',
        'color': 2,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-4p-orange/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-4_P_Orange.jpg',
    },
    {
        'name': 'TQ-4',
        'description': 'Official NRA 100 yd. small bore rifle heavy paper target.',
        'version': 'T (heavy paper)',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-4t/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-4_T.jpg',
    },
    {
        'name': 'TQ-5',
        'description': 'Official NRA 25 ft. rifle target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-5-1/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-5.jpg',
    },
    {
        'name': 'TQ-5',
        'description': 'Official NRA 25 ft. rifle target.',
        'version': '/5',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-5-5/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-5_5.jpg',
    },
    {
        'name': 'TQ-6',
        'description': 'Official NRA 25 ft. slow fire pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-6/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-6.jpg',
    },
    {
        'name': 'TQ-7',
        'description': 'Official NRA 25 ft. rapid rire pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-7/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-7.jpg',
    },
    {
        'name': 'TQ-8',
        'description': 'International 25 ft. rapid fire pistol target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-8/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-8.jpg',
    },
    {
        'name': 'TQ-9',
        'description': 'International 25 ft. free pistol target reduced from the 50 meter B-17.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tq-9/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TQ-9.jpg',
    },
    {
        'name': 'Transitional Target II',
        'description': 'US Treasury silhouette.',
        'version': '',
        'color': 3,
        'target_url_1': 'https://www.nationaltarget.com/product/transitional-target-ii-blue/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TTII_Blue.gif',
    },
    {
        'name': 'TT301R-J',
        'description': 'Target Telemetrics target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://www.nationaltarget.com/product/tt301r-j/',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TT301R-J.jpg',
    },
    {
        'name': 'TREX Rhythm-Cadence',
        'description': 'T.Rex Arms 5 yd. rhythm/cadence target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://img.trex-arms.com/wp/uploads/2021/07/RhythmDrillLevel2.pdf',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/TARhythm.png',
    },
    {
        'name': '5x5',
        'description': 'Lucky Gunner 5x5 drill target.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://loungecdn.luckygunner.com/lounge/media/5x5-drill-1.pdf',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/5x5.png',
    },
    {
        'name': 'T1C Cold Start',
        'description': 'Tier 1 Concealed cold start drill.',
        'version': '',
        'color': 0,
        'target_url_1': 'https://cdn.shopify.com/s/files/1/2298/7337/files/T1C_Cold_Start_Drill__2023.pdf?v=1677092135',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/T1C-ColdStart.png',
    },
    {
        'name': 'Runenation Cold Start',
        'description': 'Runenation cold start drill',
        'version': '',
        'color': 0,
        'target_url_1': '',
        'target_url_2': '',
        'target_url_3': '',
        'picture': 'target_images/Runenation.png',
    },
]

for target in targets:
    count += 1
    t = TargetType(**target)
    try:
        print(f"{count}: Adding '{t}' to database.")
        t.save()
        print()
        added += 1
    except IntegrityError as e:
        print(f"'{t}' already exists in the database, skipping.\n{e}\n")
    except Exception as e:
        print(f"Unable to add '{t}' to the database.\n{e}\n")

print(f"ADDED {added} TARGET(S) TO DATABASE.")
